### ISSUE TITLE
No implementation found new MapRange

### ISSUE THREAD

**Issue by grantd77** [CartoDB/mobile-sdk#328] opened 2019-11-01 00:47 UTC
Sorry if this is a repeat, I am in a rush to get this fixed.

I am getting this error in the Android app that I am updating for a client:
E/zygote: No implementation found for long com.carto.core.MapRangeModuleJNI.new_MapRange__SWIG_1(float, float) (tried Java_com_carto_core_MapRangeModuleJNI_new_1MapRange_1_1SWIG_11 and Java_com_carto_core_MapRangeModuleJNI_new_1MapRange_1_1SWIG_11__FF)

this is the offending line:

`zoomRange = new MapRange(4, 18);`

it is called in the onCreate func of a fragment. Perhaps it is in the wrong place?

I have just updated to the 4.2.2RC1 build, and was getting it in 4.2.1, so I updated to try and fix it.

I am targeting API 26 if that helps.

Does anyone have any ideas on how to fix please?

**Comment by mtehver** [comment] 2019-11-01 06:26
I guess the native library has not been initialised when you call `new MapRange(...)`. Can you check if `MapView.registerLicense` is called before you try to use any SDK method or class?

**Comment by grantd77** [comment] 2019-11-04 00:32
Hi there, I think you have hit the nail on the head, its not getting called first, I'm trying to fix an absolute frankentine's monster of an app that hadn't been touched in a while, its got missed moving things around to stop it crashing on launch.

Thank you :)

**Comment by mtehver** [comment] 2020-05-05 07:26
Closing this issue. I am assuming this was caused by using SDK classes before calling `MapView.registerLicense`.

**Closed by mtehver** 2020-05-05 07:26 UTC
