### ISSUE TITLE
[iOS] cleanup on view disposal will crash

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#479] opened 2021-12-20 13:17 UTC
I encountered an issue while adding some code to cleanup views while disposing them

So to make sure i clean up everything correctly on view disposal i added this code:
```
mapView.getLayers().clear();
```
First is that necessary? Am i sure layers are removed correctly by the mapview itself on disposal? 
Now about the crash.
The crash happens with that code in a specific usecase:
* Open a page with a mapview
* start a very long animation for setFocusPos`
* Open a second instance of that page 
* close the second instance which calls `mapView.getLayers().clear()` (while the animation in both pages is not finished)
* crash with this callstack
```
0x10f722171 sig_handler(int)
2   0x7fff6bfe0d7d _sigtramp
3   0x7fff5ae1a40a gldMergeScanlines2x2
4   0x7fff3fb22e24 glDrawElements_IMM_ES2Exec
5   0x10bde2265 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
6   0x10bdd640a -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
7   0x10bdd58b2 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
8   0x10ba949a7 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
9   0x10ba31384 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
10  0x10ba850bf -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
11  0x10ba84d58 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
12  0x10bc49ce5 -[GCDWebServerURLEncodedFormRequest .cxx_destruct]
13  0x7fff4eb6740c -[GLKView _display:]
14  0x7fff28947691 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
15  0x7fff288830ca CA::Context::commit_transaction(CA::Transaction*, double, double*)
16  0x7fff288bac47 CA::Transaction::commit()
17  0x7fff288bbfc8 CA::Transaction::flush_as_runloop_observer(bool)
18  0x7fff20368c77 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
19  0x7fff2036349c __CFRunLoopDoObservers
20  0x7fff20363a4c __CFRunLoopRun
21  0x7fff20363103 CFRunLoopRunSpecific
22  0x7fff2c851cd3 GSEventRunModal
23  0x7fff24ffbe63 -[UIApplication _run]
24  0x7fff25000a53 UIApplicationMain
25  0x11010e4f5 ffi_call_unix64
```
Maybe the call to `mapView.getLayers().clear();` is actually not needed (no crash anymore). But i thought it would be useful to report cause their still might be an issue somewhere causing that crash.

**Comment by mtehver** [comment] 2021-12-20 15:18
@farfromrefug Sure, any example helps. The smaller the better.

**Comment by farfromrefug** [comment] 2021-12-20 15:39
@mtehver https://github.com/jarmani/mapleak/tree/main
I added small instruction which, if no specific error. Should be enough to run the app
* once opened. Click on Map then map again. Go back => crash
* once you ve run it once, stop the running `ns` command. Go into `platforms/ios`. You can open the xcode workspace, modify it to use your local carto dev build project, run it to debug.

Hope it is going to work on the first run!

**Comment by jarmani** [comment] 2021-12-20 16:54
@mtehver I added you to jarmani/mapleak (private)

**Comment by farfromrefug** [comment] 2021-12-20 18:12
@jarmani shoot did not think.it was private :p

**Comment by mtehver** [comment] 2021-12-23 12:32
@farfromrefug Thanks for the demo project and instructions, it helped a lot. I have pushed a fix for this into 'develop' branch.

**Comment by jarmani** [comment] 2022-01-06 12:53
I can't reproduce the crash with 4.4.4RC1, thanks !

**Closed** 2022-01-06 14:19 UTC
Labels: bug
