### ISSUE TITLE
Samsung tablet crash

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#5] opened 2016-06-08 08:44 UTC
Started map view with focus to Berlin, zoom 0, zoomed in up to zoom 15, then back; closed activity, started again, repeated 5-6 times. Activity crashed with attached log.
[samsung_tablet_crash.txt](https://github.com/CartoDB/mobile-sdk/files/304362/samsung_tablet_crash.txt)

**Comment by mtehver** [comment] 2016-10-28 09:42
Unable to reproduce this with the latest SDK version, thus closing this for now. This could have also been related to previous Galaxy Tab S2 firmware version, as we have have updated the device now to Android 6.0.1

**Closed by mtehver** 2016-10-28 09:42 UTC
