### ISSUE TITLE
wrong vector tile element selected on click

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#314] opened 2019-08-17 12:19 UTC
I found out that sometimes even if you actually click on vector element, it is another one which is first returned by listener.
In this particular case you can see that feature selected in on the side of the street. The funny thing here is that the poi actually returned has the same name ! (there are 2 Gilbert Joseph around there).
I know i am also getting this a lot while selecting mountain peaks (see second video)

![sdk_gphone_x86PSR1 180720 061mguillon08172019141615](https://user-images.githubusercontent.com/655344/63211582-97579580-c0f9-11e9-90d6-12399800fb34.gif)
![sdk_gphone_x86PSR1 180720 061mguillon08172019141857](https://user-images.githubusercontent.com/655344/63211619-fcab8680-c0f9-11e9-99f9-dc99d72d2391.gif)

**Comment by soheil-sf** [comment] 2019-08-17 14:20
Duplicate of #312

**Comment by mtehver** [comment] 2019-08-22 08:25
@soheil-sf Looks like the same issue. Unfortunately I have not been able to reproduce this myself. A small test (with source code/project) and instructions how to reliably see the issue would be really helpful.

**Comment by farfromrefug** [comment] 2019-08-22 09:17
@mtehver i think the best thing is to share the theme
[mapsme.zip](https://github.com/CartoDB/mobile-sdk/files/3529276/mapsme.zip)
Now go around the south east of Grenoble 
45.1942748" N, 5.7316321" E
You should be able to reproduce the issue with VectorTileElementListener
The idea is to compare ```getClickPos()``` and ```feature.getGeometry().getCenterPos()```
Sorry right now my apps are using a cross platform framework so not easy to share

**Comment by jaakla** [comment] 2019-08-22 18:40
Can you check object unique ID (osm_id) property ? Maybe this is same (or missing), so it is data issue really.

**Comment by farfromrefug** [comment] 2019-08-23 11:32
@jaakla i checked and they dont have the same osm_id.

**Comment by mtehver** [comment] 2019-08-23 18:20
@farfromrefug SDK 4.2.1RC2 is now out and should fix this. There were two related issues, the tricky one was caused by labels merged from multiple tiles and not keeping track of the original source.

**Comment by mtehver** [comment] 2019-08-30 11:23
Closing this as 4.2.1 is out and should fix this.

**Closed by mtehver** 2019-08-30 11:23 UTC

**Comment by farfromrefug** [comment] 2019-10-15 14:08
@mtehver i actually see that issue again with the develop branch. Did you change something in the late commits?

**Comment by mtehver** [comment] 2019-10-15 17:43
@farfromrefug No, there should no changes that could cause this. I will do some tests and review the changes, though.

**Comment by farfromrefug** [comment] 2019-10-16 07:10
@mtehver This also might come from me finding other cases.
Here is the style i am using. I remember that i clearly saw this on zoom around 10 when there was a few national parks on sight (south east of France for example). The selected element was really far from the click position. May be we could have a max distance (in screen pixels)?
[mapsmexml.zip](https://github.com/CartoDB/mobile-sdk/files/3732897/mapsmexml.zip)
