### ISSUE TITLE
Improving adding/removing vector elements with fade in/out

### ISSUE THREAD

**Issue by nole87** [CartoDB/mobile-sdk#29] opened 2016-08-27 12:27 UTC
Adding or removing vector elements on map now are hard, so when they are added or removed it’s not so hard, to make some small animation like fade in/out, it’s a not a big task in my opinion and it's something like standard in now days! :)

**Comment by mtehver** [comment] 2017-03-01 08:46
Duplicate of #58, currently implemented for billboard in feature/animatedvectorelements branch.

**Comment by mtehver** [comment] 2017-11-08 09:32
Closing this. Implemented now in SDK 4.1 for Markers/Texts/Popups.

**Closed by mtehver** 2017-11-08 09:32 UTC
