### ISSUE TITLE
Where to get already packed MBTiles? Or how to generate them?

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#188] opened 2018-02-27 10:02 UTC
Hello,

I've tried to load vector MBTiles from https://openmaptiles.com/ and they looked unstyled (I applied the CARTO_BASEMAP_STYLE_DEFAULT style). Am I doing something wrong here?

Perhaps those MBTiles aren't appropriate for the Carto SDK. If that's the case...it will be fine if someone points out a way to do it. I can investigate and do it by myself.

I have been doing research about this topic for a lot of months with no luck. And I really love the Carto SDK. I'd even consider using the paid plan, but it's too expensive at least at the beginning for me.

This is the main code of my Android activity:

```
addBaseLayer(CartoBaseMapStyle.CARTO_BASEMAP_STYLE_DEFAULT);
TileDataSource source = createTileDataSource();
MBVectorTileDecoder decoder = getDecoderFromCurrentLayer();
clearLayers();
addNewLayer(source, decoder);

private void addBaseLayer(CartoBaseMapStyle style)
{
        CartoOnlineVectorTileLayer base = new CartoOnlineVectorTileLayer(style);
        mapView.getLayers().add(base);
}

private TileDataSource createTileDataSource()
{
    MBTilesTileDataSource tileDataSource = null;
    try {
            String localDir = getExternalFilesDir(null).toString();
            String path = localDir + "/" + "2017-07-03_spain_barcelona.mbtiles";
            tileDataSource = new MBTilesTileDataSource(path);
    } catch (IOException e) {
            // Handle exception
    }
}

private MBVectorTileDecoder getDecoderFromCurrentLayer() {
        return (MBVectorTileDecoder)((VectorTileLayer)mapView.getLayers().get(0)).getTileDecoder();
}

private void clearLayers()
{
        mapView.getLayers().clear();
}

private void addNewLayer(TileDataSource source, MBVectorTileDecoder decoder)
{
        VectorTileLayer layer = new VectorTileLayer(source, decoder);
        mapView.getLayers().insert(0, layer);
}
```

Attached you'd find 3 screenshots of what I see from different zoom levels:

![screenshot_20180227-105625](https://user-images.githubusercontent.com/19690868/36722332-8b5ec174-1bad-11e8-8776-629471991147.png)
![screenshot_20180227-105635](https://user-images.githubusercontent.com/19690868/36722333-8b7ca3ba-1bad-11e8-9a98-f50ffee5aaa5.png)
![screenshot_20180227-105645](https://user-images.githubusercontent.com/19690868/36722335-8b967bbe-1bad-11e8-8e61-c59fee7851ae.png)

**Comment by jaakla** [comment] 2018-02-27 12:13
It seems that you use older SDK version, you should use 4.1.0 or newer for openmaptiles styling.

**Comment by mtehver** [comment] 2018-02-27 13:34
With some work you could use 'MapBox Studio Classic' styles from [https://github.com/openmaptiles/openmaptiles](https://github.com/openmaptiles/openmaptiles). 

But they will probably need manual fixing and will not run as fast and will not look as nice as our built-in styles. No continous handling of line widths, for example.

**Comment by carlos-mg89** [comment] 2018-02-27 14:15
Would you kindly tell me how should I pack one of these MapBox Studio Classic styles to be compatible with CartoDB please? I assume I should load an AssetPackage, or a ZippedAssetPackage. But haven't found the way to do that.

**Comment by mtehver** [comment] 2018-02-28 10:08
@carlos-mg89 I will add a section to the Wikipage with instructions. This question has been asked several times before, so I think some guide is useful. I will send a link once the wikipage is up.

**Comment by mtehver** [comment] 2018-02-28 12:17
@carlos-mg89 The preliminary info about creating custom styles is [here](https://github.com/CartoDB/mobile-sdk/wiki/Creating-custom-basemap-styles)

**Comment by farfromrefug** [comment] 2018-03-06 10:04
@mtehver great stuff!
I actually managed to find prebuild mapbox studio classic versions here: 
https://mapbox.s3.amazonaws.com/mapbox-studio/index.html
And it's really easy to work with carto sources using this:
http://mobile-api.carto.com/maps/v2/carto.streets/1/tiles.json

Wouldn't it be to actually fork mapbox-studio-classic to create a carto version?
It should be fairly easy. And you could even easily add support for Carto specific CSS properties.
And have custom export/save.

**Comment by jaakla** [comment] 2018-03-12 13:35
This would be technically possible, but we don't have it as high priority for now.

**Comment by jaakla** [comment] 2018-03-12 13:41
Closing this as it is duplicate of https://github.com/CartoDB/mobile-sdk/issues/174

**Closed by jaakla** 2018-03-12 13:41 UTC
Labels: enhancement
