### ISSUE TITLE
Android Emulator black marker (Win 10 only)

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#139] opened 2017-10-06 19:59 UTC
Default marker is shown as totally black rectangle in some Android emulators under Win10, regardless of style, even with default style. At least affected machine was with Intel GPU.

@mtehver to be checked if we can replicate and do something for it. Some developers (at least students) use win10+android emulator combination.

**Comment by mtehver** [comment] 2017-10-20 07:37
Most likely an issue with broken GL/DX drivers on specific Windows machines using Intel integrated graphics. Probably not worth investigating, as does not affect real devices.

**Comment by mtehver** [comment] 2018-03-13 12:07
I am closing this as unable to reproduce with SDK 4.1.2 and HAXM 6.2.1/Android Emulator 27.1.12. Using Windows 10Pro and NVidia GT630. There have been small tweaks to the shaders in the SDK after this was reported but the most likely explanation is that the issue has been fixed in HAXM by Google or Intel.

**Closed by mtehver** 2018-03-13 12:07 UTC
Labels: wontfix
