### ISSUE TITLE
CartoSDK Metal version has issues with `NTVectorElementEventListener`

### ISSUE THREAD

**Issue by kamil-tomaszewski** [CartoDB/mobile-sdk#470] opened 2021-11-09 22:19 UTC
Hi.
Following up on https://github.com/CartoDB/mobile-sdk/issues/461. I've successfully transitioned our project from using the GLKit version to the Metal one. However, that produced a problem with listening for touch events on vector objects. Everything works fine on the simulator and everything works fine as well on devices apart from the "Pluses". I'm able to reproduce this issue on the sample project, namely `AdvancedMap.Swift`. If you replace the default Carto pod with `pod 'CartoMobileSDK-Metal', '4.4.2'` and run the app on an iPhone 6 Plus / 7 Plus or 8 Plus device you'll notice that the vector objects are not triggering `override func onVectorElementClicked(_ clickInfo: NTVectorElementClickInfo!) -> Bool` for some reason.

Could you please assist or at least confirm this issue and propose a potential workaround?

**Comment by mtehver** [comment] 2021-11-10 08:44
Thanks for reporting this. I think this has something to do with 'virtual' and 'native' resolution mismatch that occurs only on 'plus' devices (and not in simulators of these devices). We currently do not have any such devices on hand, we have ordered one and will get it within a week. I will keep you posted and we will likely publish a RC version (with a fix) within 2 weeks.

**Comment by kamil-tomaszewski** [comment] 2021-11-10 09:24
Thank you!

**Comment by mtehver** [comment] 2021-11-15 06:13
I finally got a test device for this and can confirm the issue. The issue is due to a different handling of 'scaling factor' and 'native scaling factor' in `GLView` vs `MGLView`.  4.4.3RC1 with a fix is planned early next week. Thanks again for reporting this.

**Comment by mtehver** [comment] 2021-11-24 11:32
@kamil-tomaszewski  4.4.3 RC1 is now available and includes the fix.

**Comment by kamil-tomaszewski** [comment] 2021-11-29 14:31
@mtehver I've tried to test it by doing:
`pod 'CartoMobileSDK-Metal', :git => 'https://github.com/CartoDB/mobile-sdk.git', :tag => 'release/v4.4.3-rc.1'`
but I got
> [!] Unable to find a specification for 'CartoMobileSDK-Metal'.

Is there any way I could test it?

**Comment by mtehver** [comment] 2021-11-30 07:57
@kamil-tomaszewski Just use `pod 'CartoMobileSDK-Metal', '4.4.3-rc.1'`. We publish all our releases and RCs to the official Cocoapods repository.

**Comment by kamil-tomaszewski** [comment] 2021-12-02 09:07
@mtehver I can confirm that this version works properly now. Thanks!

**Comment by mtehver** [comment] 2021-12-15 08:18
Closing this, final 4.3.3 with the fix included is now released.

**Closed by mtehver** 2021-12-15 08:18 UTC
Labels: bug
