### ISSUE TITLE
MapView baseMapView is sometimes null for android

### ISSUE THREAD

**Issue by snijsure** [CartoDB/mobile-sdk#89] opened 2017-03-16 13:21 UTC
I am using `com.carto:carto-mobile-sdk:4.0.1@aar` for my Android application, and I sometime see following exception.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.carto.components.Options com.carto.ui.BaseMapView.getOptions()' on a null object reference
```

My calling code this:
```                    
  if (vMap != null && vMap.getOptions() != null) {
}
```

Which seems to hit this code

```
    public Options getOptions() {
        return this.baseMapView.getOptions();
    }
```

Since baseMapView is private member caller can not check if baseMapView is null can getOptions code update to check of null-ness or importantly why would baseMapView suddenly go null?

We do call MapView::delete in the onDestroyView of the fragment that creates mapView. It seems some how methods on MapView are being called even after onDestroyView is called. Is there better way to destroy MapView?

```
  @Override
  public void onDestroyView() {
    if(vMap != null) {
      vMap.cancelAllTasks();
      vMap.setMapEventListener(null);
      for (int i = 0; i < vMap.getLayers().count(); i++) {
        Layer layer = vMap.getLayers().get(i);
        if (layer instanceof VectorLayer) {
          ((VectorLayer) layer).setVectorElementEventListener(null);
          layer.delete();
        }
      }
      vMap.delete();
      System.gc();
    }
    super.onDestroyView();
  }
```

**Comment by mtehver** [comment] 2017-03-17 19:17
This is most likely caused by calling mapView.getOptions() after mapView.delete(). delete method disconnects Java objects from native objects and sets JNI references to null. Technically, calling delete methods is not required, but can speed up native memory release. Doing System.gc() should be actually enough and is definitely safe, as you do not need to worry about object lifetimes.

**Comment by mtehver** [comment] 2017-11-08 09:29
Closing this, as this was most likely caused by manual call to 'delete' method.

**Closed by mtehver** 2017-11-08 09:29 UTC
