### ISSUE TITLE
Build error (Android)

### ISSUE THREAD

**Issue by pbhattacharya123** [CartoDB/mobile-sdk#260] opened 2018-12-13 18:49 UTC
When running build-android.py, I am getting an errror:

**This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj]**

Pasting detailed log below:

$ python build-android.py  --profile standard
-- Building for: Visual Studio 10 2010
CMake Deprecation Warning at C:/Program Files (x86)/CMake/share/cmake-3.13/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  C:/Development/Carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1183 (CMAKE_FORCE_C_COMPILER)
  C:/Program Files (x86)/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

CMake Deprecation Warning at C:/Program Files (x86)/CMake/share/cmake-3.13/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  C:/Development/Carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1195 (CMAKE_FORCE_CXX_COMPILER)
  C:/Program Files (x86)/CMake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

-- Creating directory, C:/Development/Carto/mobile-sdk/build/android-x86/freetype/include.
-- Creating C:/Development/Carto/mobile-sdk/build/android-x86/freetype/include/ftconfig.h.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE

-- Build files have been written to: C:/Development/Carto/mobile-sdk/build/android-x86
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2018-12-13 1:32:52 PM.
Project "C:\Development\Carto\mobile-sdk\build\android-x86\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Development\Carto\mobile-sdk\build\android-x86\ALL_BUILD.vcxproj" (1) is building "C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(283,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj]
Done Building Project "C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Development\Carto\mobile-sdk\build\android-x86\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Development\Carto\mobile-sdk\build\android-x86\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj" (default target) (2) ->
(PrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(283,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\Development\Carto\mobile-sdk\build\android-x86\ZERO_CHECK.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.50
Error while executing cmake (path C:/Development/Carto/mobile-sdk/build/android-x86):
cmake --build .

**Comment by mtehver** [comment] 2019-03-27 19:01
Very strange message. In general we do not support building Android on Windows (in theory it could work, but we have never tested it). It seems that cmake picks up Visual Studio as an target, not Android NDK. We have changed cmake toolchain files for SDK 4.2 (currently develop branch), maybe it is worth a try. Note that due to major internal changes between NDK versions, master branch expects really old NDK version (13c should be safe). 'develop' branch should work with up to 17b, but not with the latest version currently.

**Comment by mtehver** [comment] 2019-03-28 14:11
I have reproduced the issue and fixed it in develop branch. But for know I would suggest using Windows Subsystem for Linux to build the SDK on Windows.

**Comment by pbhattacharya** [comment] 2019-03-28 15:32
Thank you!

**Comment by mtehver** [comment] 2019-05-27 16:13
Closing this, SDK 4.2 for Android can be built on Windows. It needs NDK r20 and lots of command-line options, though.

**Closed by mtehver** 2019-05-27 16:13 UTC
Labels: SDK-4.2, bug
