### ISSUE TITLE
Out of memory errors 

### ISSUE THREAD

**Issue by snijsure** [CartoDB/mobile-sdk#85] opened 2017-03-08 21:07 UTC
I am currently using 4.0.1RC3 and see following error, could library handle this error by using "place holder bitmap`?

`
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:620)
       at com.carto.utils.BitmapUtilsModuleJNI.BitmapUtils_createAndroidBitmapFromBitmap(Unknown Source)
       at com.carto.utils.BitmapUtilsModuleJNI.BitmapUtils_createAndroidBitmapFromBitmap(Unknown Source)
       at com.carto.utils.BitmapUtils.createAndroidBitmapFromBitmap(Unknown Source)
       at com.lonelyplanet.guides.common.util.NutiteqHelper$2.onMapRendered(SourceFile:143)
       at com.carto.renderers.RendererCaptureListenerModuleJNI.SwigDirector_RendererCaptureListener_onMapRendered(Unknown Source)
       at com.carto.ui.BaseMapViewModuleJNI.BaseMapView_onDrawFrame(Unknown Source)
       at com.carto.ui.BaseMapView.onDrawFrame(Unknown Source)
       at com.carto.ui.MapView.onDrawFrame(Unknown Source)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

**Comment by mtehver** [comment] 2017-03-10 09:35
Is this something you can reproduce easily? If possible, we would like to have a testcase.

A possible workaround for out-of-memory issues is to manually call System.gc() after large objects are no longer in use (for example, large Bitmaps or MapView instance). The reason is that Java Runtime Environment sees most SDK objects as taking only very little of Java heap and does not know how much native heap is used by the objects. Doing manual GC after closing MapView activity  or after capturing a screenshot may really help.

**Comment by mtehver** [comment] 2018-02-28 14:32
I am closing this as this was probably an app-specific issue regarding memory handling, not specific to the Mobile SDK.

**Closed by mtehver** 2018-02-28 14:32 UTC
