### ISSUE TITLE
4.2.0 feedback

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#279] opened 2019-04-26 14:07 UTC
Hi,

Just compiled and ran the develop branch. Now that there is the LicenseManager ;)

The first thing is that the standard profile does not include the LicenseManager which makes the build fail. Adding ```_CARTO_LICENSEMANAGER_SUPPORT``` makes it build just fine.

Now the first thing i did with it was to try ```EPSG4326```
I test on android
I do :
``` java
mapView.getOptions().setBaseProjection(new com.carto.projections.EPSG4326());
mapView.setFocusPos(new com.carto.core.MapPos(6, 45), 0); // Grenoble, France
```
and i see that in the logs:
```
04-26 15:56:41.178   794   969 E carto-mobile-sdk: ViewState::setFocusPos: Invalid coordinates 0, nan, 0
04-26 15:56:41.178   794   969 E carto-mobile-sdk: ViewState::setCameraPos: Invalid coordinates 0, nan, 0.03125
```
then a few lines later:
```
04-26 15:56:41.182   794   969 E carto-mobile-sdk: ViewState::setCameraPos: Invalid coordinates 17476.3, nan, 0.097527
04-26 15:56:41.182   794   969 E carto-mobile-sdk: ViewState::setFocusPos: Invalid coordinates 17476.3, nan, 0
```

Am i missing something, shouldn't that work?

Will report more here as i find issues

**Comment by mtehver** [comment] 2019-04-27 04:47
Thanks for testing! Both issues should be fixed now.

**Comment by farfromrefug** [comment] 2019-04-27 18:22
I can confirm that both issues are fixed! Will test more

**Comment by farfromrefug** [comment] 2019-04-28 07:55
@mtehver found out a few more issues in planar mode (not tested spherical yet). Still using ```EPSG4326``` and running on Android.
- ```mapView.getOptions().setRestrictedPanning(true)```  seems to break everything. The map is stuck at zoom 24 and i cant zoom out. The weird thing is it seems i only see this in the emulator
- gesture "velocity" seems broken. When i do double tap to zoom, if i give velocity while leaving the screen, the velocity induce a panning instead of a zoom. Let me know if you dont see what i mean.
- if i use ```setVectorTileEventListener``` on a layer for which the ```dataSource``` has a ```EPSG4326``` projection, the ```VectorTileClickInfo``` does not return positions in ```EPSG4326```
- got some black in the sky when i use ```mapView.getOptions().setDrawDistance(8)```
![Screenshot_1556437476](https://user-images.githubusercontent.com/655344/56860750-4a10b600-699a-11e9-8e67-7d24e6f6d28a.png)

Also some globe issues:
- markers does not maintain their rotation (same settings work in planar: ```orientationMode: BillboardOrientation.GROUND,  scalingMode: BillboardScaling.SCREEN_SIZE```)
![Screenshot_1556437785](https://user-images.githubusercontent.com/655344
- after sometimes moving the map, the 0 rotation is lost. Especially for me it happens when i select a pos and use ```setFocusPos```
before:
![Screenshot_1556437743](https://user-images.githubusercontent.com/655344/56860873-7416a800-699b-11e9-9dd2-fe0a5d54bbc6.png)
after a while and with ```setMapRotation(0)```
![Screenshot_1556437952](https://user-images.githubusercontent.com/655344/56860876-7c6ee300-699b-11e9-8c13-3f75a2f64594.png)


That's it for now. Let me know if i can help in any way. Now i need to find a way to setup a dev env for live MobileSDK dev so that i can help you more.

**Comment by mtehver** [comment] 2019-04-28 12:01
@farfromrefug  Thanks for the feedback. Few comments:

1) Will try to reproduce the restricted panning issue. How did you configure the emulator?

2) If you could elaborate the gesture velocity issue, that would help

3) regarding `setVectorTileEventListener` - I am not exactly sure what you mean here. Note that you can not have EPSG4326 vector tiles, we do not support them. Thus if you have vector tile listener, you need to have EPSG3857 projection and the click event coordinates are based on this projection. 

4) `setDrawDistance` is somewhat undocumented and not well defined method that we may remove in the future. I may have a quick look but not sure I will do anything about this

5) Could you re-upload the screenshot about markers? The link seems broken

6) Will check the rotation issue after panning

**Comment by farfromrefug** [comment] 2019-04-28 15:13
@mtehver 
1. No specific configuration i think. Here is a screenshot if it can help
<img width="1300" alt="Screen Shot 2019-04-28 at 16 53 10" src="https://user-images.githubusercontent.com/655344/56866130-279c8e00-69d6-11e9-85fa-dfdb551365d4.png">
2. by veolicty mean gesture with deceleration upon touch up. So for the issue:
- start double tap to zoom
- while zooming raise your finger while swiping
- you end up with some "velocity" that should slowly decelerate while zooming.
Instead it creates a pan gesture during deceleration.
Can make a video (not working right now)
3. I mean that that when in ```onVectorTileClicked``` and ```onVectorElementClicked``` the ```featureClickPos``` and ```clickPos``` are using ```EPSG3857```. I get that tile can't use anything else put ```EPSG3857```. In the meantime there should be a way to make so that the listener return ```EPSG4326``` for feature pos. Will fix that on my side for now.
4. ok used it actually to limit tile query
5. here you go
![Screenshot_1556463646](https://user-images.githubusercontent.com/655344/56866401-efe31580-69d8-11e9-94a0-19bf4fd5a515.png)
6. thanks

**Comment by farfromrefug** [comment] 2019-04-28 16:48
Actually i though about 3, it is a bit of an issue. What i want is for the ```onVectorTileClicked``` and ```onVectorElementClicked``` positions to be in the map projection system.
No problem for them to be in ```EPSG3857```, but right now there is no way to say "convert a MapPos" from one projection system to another.
For example something like ```Projection.fromMapPos(mapPos: MapPos, originalProjection: Projection) : MapPos```.
This is important because i am writing a framework on top of the SDK (Nativescript wrapper). So i dont want to decide for the user the projection it uses for the map, but i want to make sure if he choses one, every feature and map positions are going to be in that projection system.

**Comment by mtehver** [comment] 2019-04-28 17:11
@farfromrefug Regarding conversion from one projection to another: you can do it using `Projection.toWgs84` and `Projection.fromWgs84` methods. If you want your coordinates in EPSG4326, you actually only need to call `toWgs84`.

In general, there is a 'global coordinate' projection that is used for global map event handler and for setting focus pos, for example. And there are layer-specific projections that are used for layer coordinates and layer event handlers.

Thanks for the details about other issues, will investigate these ASAP.

**Comment by farfromrefug** [comment] 2019-04-29 14:45
@mtehver about the projection issue. Are you saying that whatever projection you add in the future. doing:
```java
// pos1 being in proj1 format
MapPos res = proj2.fromWgs84(proj1.toWgs84(pos1));
//res is in proj2 format.
```
will work and is the right to convert pos1 from proj1 to proj2?
Thanks

**Comment by mtehver** [comment] 2019-04-30 08:47
@farfromrefug Regarding the coordinate conversion - yes, your snippet works with all projections. 

About other issues:

1) I am unable to reproduce the restricted panning issue in emulator. Any chance you were using older build in emulator?

2) Very good find, should be fixed now. 

3) About marker rotation when using `BillboardOrientation.GROUND`. Actually markers with this orientation mode should rotate when the map rotates. Perhaps the issue was here that if you used `getRotation` method in with your `MapView`, you got 0? This was a bug, rotation value was not properly updated when panning is globe mode

4) The map rotation issue - this is related to the previous issue, I think. The problem is that panning in globe mode changes rotation. I have seen some globe engines try to avoid that but that creates major issues when panning over a pole, for example. The actual bug was related to 'rotation' attribute value, 'rotation' angle was not updated when panning and this is now fixed.

Thanks again for testing!

**Comment by farfromrefug** [comment] 2019-05-01 08:26
@mtehver all seems fixed in RC1!!! Thank you so much

I saw in RC1 that ```AssetPackage``` constructor without argument is protected, could you make it public?

**Comment by farfromrefug** [comment] 2019-05-01 12:51
@mtehver found what i think is an issue with ```AssetPackage``` loading of assets.
I wrote my own custom AssetPackage class which reads directly from a directory (useful for live editing of style). I implemented ```getAssetNames``` and ```loadAsset```
I also added logs there to see what is happening
The issue is that it seems that some assets are loaded multiple times.
```
getAssetNames done 17: README.md,fonts/LICENSE_OFL.txt,fonts/Montserrat-Italic.ttf,fonts/Montserrat-Medium.ttf,fonts/Montserrat-Regular.ttf,fonts/Montserrat-SemiBold.ttf,fonts/NotoSans-Plus.ttf,images/city-square.png,images/dark-matter-square-3.png,shared/admin.mss,shared/hydro.mss,shared/labels.mss,shared/landuse.mss,shared/roads.mss,shared/terrain.mss,voyager.json,voyager/style.mss
```

Now here is my log while loading the map 
```
JS: loadAsset done in 2 ms for voyager.json
JS: loadAsset done in 1 ms for voyager.json
JS: loadAsset done in 1 ms for voyager/style.mss
JS: loadAsset done in 0 ms for shared/admin.mss
JS: loadAsset done in 1 ms for shared/hydro.mss
JS: loadAsset done in 4 ms for shared/landuse.mss
JS: loadAsset done in 1 ms for shared/roads.mss
JS: loadAsset done in 1 ms for shared/labels.mss
JS: loadAsset done in 1 ms for shared/terrain.mss
JS: loadAsset done in 1 ms for fonts/LICENSE_OFL.txt
JS: loadAsset done in 4 ms for fonts/Montserrat-Italic.ttf
JS: loadAsset done in 3 ms for fonts/Montserrat-Medium.ttf
JS: loadAsset done in 2 ms for fonts/Montserrat-Regular.ttf
JS: loadAsset done in 6 ms for fonts/Montserrat-SemiBold.ttf
JS: loadAsset done in 4 ms for fonts/NotoSans-Plus.ttf
JS: loadAsset done in 2 ms for voyager.json
JS: loadAsset done in 1 ms for voyager.json
JS: loadAsset done in 1 ms for voyager/style.mss
JS: loadAsset done in 1 ms for shared/admin.mss
JS: loadAsset done in 2 ms for shared/hydro.mss
JS: loadAsset done in 1 ms for shared/landuse.mss
JS: loadAsset done in 1 ms for shared/roads.mss
JS: loadAsset done in 1 ms for shared/labels.mss
JS: loadAsset done in 0 ms for shared/terrain.mss
```
Almost all my assets, except the fonts are loaded twice. The json config is even loaded 4 times.
I really don't think it has anything to do with my implementation. Could it be something like concurrent loading of resources from multiple threads?

Right now it taks 42ms to load all. Without those duplicate loadings it would take only 31ms. So a 25% gain.

Sorry i cant really post sample code as it is all written on JS  :s even the custom ```AssetPackage``` class [here](https://github.com/farfromrefug/nativescript-carto/blob/master/src/utils/utils.android.ts#L197)

**Comment by mtehver** [comment] 2019-05-02 11:05
@farfromrefug Thanks! I will take a closer look at the `AssetPackage` issue this next week.

**Comment by mtehver** [comment] 2019-05-09 09:05
@farfromrefug Regarding `AssetPackage` - are you using `CartoOnlineVectorTileLayer`? This class is somewhat special as it does online check for an updated style asset. Perhaps that is what is happening here? I did some tests with 4.2.0RC1 and the only file that is loaded multiple times is 'voyager.json'.

About `AssetPackage` default constructor being protected. That is the convention we use for abstract base classes. This should be no problem, as derived classes are able to use it.

**Comment by farfromrefug** [comment] 2019-05-09 09:28
@mtehver No i am not using ```CartoOnlineVectorTileLayer```. Only a ```VectorTileLayer```
Could it be related to the content of ```voyager.json```? 
here is mine:
```json
{
  "layers": [
    "housenumber", 
    "water_name", 
    "transportation_name", 
    "poi", 
    "place", 
    "transportation", 
    "building", 
    "aeroway", 
    "waterway", 
    "water", 
    "mountain_peak", 
    "boundary", 
    "contour", 
    "hillshade",
    "park", 
    "landuse", 
    "landcover"
  ], 
  "styles": [
    "voyager/style.mss", 
    "shared/admin.mss", 
    "shared/hydro.mss", 
    "shared/landuse.mss", 
    "shared/roads.mss", 
    "shared/labels.mss",
    "shared/terrain.mss"
  ], 
  "nutiparameters": {
    "lang": {
      "default": "en"
    }, 
    "buildings": {
      "default": 1, 
      "values": {
        "1": 1, 
        "0": 0, 
        "2": 2
      }
    }, 
    "fallback_lang": {
      "default": "en"
    }, 
    "texts3d": {
      "default": "nutibillboard", 
      "values": {
        "1": "nutibillboard", 
        "0": "point"
      }
    }, 
    "markers3d": {
      "default": "nutibillboard", 
      "values": {
        "1": "nutibillboard", 
        "0": "point"
      }
    }, 
    "shields3d": {
      "default": "nutibillboard", 
      "values": {
        "1": "nutibillboard", 
        "0": "point"
      }
    }
  }, 
  "name": "voyager"
}
```

About the AssetPackage constructor i managed to go around it so don't change a thing!
thanks

**Comment by mtehver** [comment] 2019-05-09 10:52
@farfromrefug Any chance you are using any 'setXXX' methods of `VectorTileDecoder`? Most of these basically reload/rebuild the style.

**Comment by farfromrefug** [comment] 2019-05-09 17:04
@mtehver  yes I am. but any set call I do is done before passing it to the layer. is the style loading before or after passing it to the layer constructor?

**Comment by mtehver** [comment] 2019-05-10 07:42
@farfromrefug Style is loaded already during construction time. There are numerous error conditions that may occur and doing it lazily/in another thread would not allow to properly signal these.

**Comment by farfromrefug** [comment] 2019-05-10 08:13
@mtehver ok get it. Any way around this? The ability to set properties before loading the style ? like a  ```setReadyToLoad```?
This might quite ugly performance consequences as loading/parsing ```mss``` can be long

**Comment by farfromrefug** [comment] 2019-05-21 09:36
@mtehver I added some logs on my MBVectorTileDecoder and i am actually not calling any setter method that would trigger multiple reloads of the ```mss```. I guess i need to make a test android class and run it in the android sampes app to see how it goes.

Now more feedbacks:
- there seems to be a strange rule on the ```VectorTileEventListener``` ```onVectorTileClicked``` events. i am implementing it to allow clicking on mountains peeks for example. I only returns true when the feature seems interesting. My issue is the order in which the feature are passed to the listener.
Here is my log:
```
JS: onVectorTileClicked distanceFromClick:320.58797182788214, elevation:4808, name:Mont Blanc - Monte Bianco
JS: onVectorTileClicked distanceFromClick:368.876611022694, elevation:1059, name:Crêt de Pont
JS: onVectorTileClicked distanceFromClick:293.0743751618463, elevation:4061, name:Gran Paradiso
JS: onVectorTileClicked distanceFromClick:91.27315828753005, elevation:3100, name:Petit Pinier
JS: onVectorTileClicked distanceFromClick:53.13383724176187, elevation:3020, name:Pic du Mas de la Grave
JS: onVectorTileClicked distanceFromClick:639.2852500728371, elevation:1699, name:Signal de Finiels
JS: onVectorTileClicked distanceFromClick:45.06497959413595, elevation:3427, name:Aiguille du Goléon
```
As you can see there does not seem to be a rule for the order. It should be the distance. From a user perspective it should be closest first the moving away.

What do you think? is the current order the order from the tile data?

- ```marker-fill``` color does not seem to work for svg markers. Is that to be expected ? (might have been the same in older sdks, was not using it!)

- for now ```NTVectorTileEventListener``` does not seem to work for me. No event. Needs to run more tests though.

**Comment by mtehver** [comment] 2019-05-21 10:08
@farfromrefug The order of `VectorTileEventListener` callbacks is broken (reversed) in RC.2 (was ok in RC.1). It is fixed in master since yesterday. 

Regarding the texts - text size is not the first parameter used for deciding what to keep/hide. If you reorder your rules and put contour texts last, it should work. If not, then I need to take a closer look at your style.

`marker-fill` currently works only for markers that are not defined via external file. This is not a regression vs 4.1.x, more like an internal limitation of the SDK.

Thanks for testing!

**Comment by farfromrefug** [comment] 2019-05-21 10:12
@mtehver even reversed the order seems not right. It is not in order of distance as you can see in my logs.
Regarding the texts, the rules for contours texts and peaks are in different style files. Though even with the right order in the ```json``` ```styles``` property, it does the same. Is the order of ```mss``` in the ```styles``` is respected while loading the rules?

Ok about the color ! Will color my svgs.

Thanks

**Comment by mtehver** [comment] 2019-05-21 12:14
@farfromrefug About the order - how do you calculate 'distanceFromClick'? The order in which `onVectorTileClicked` should be exactly reverse of rendering order.

About the texts, I oversimplified before. The priority is based on layer order, but depends when the layer is 'mentioned' first in css files. The ordering logic is based on Mapnik ordering.

**Comment by farfromrefug** [comment] 2019-05-21 12:21
@mtehver for the distance:
```
function distance(pos1: ScreenPos, pos2: ScreenPos) {
   return  Math.sqrt(Math.pow(pos1.x - pos2.x, 2) + Math.pow(pos1.y - pos2.y, 2));
}
const distanceFromClick = distance(map.mapToScreen(position), map.mapToScreen(featurePosition));
```

Now about the text, there is something wrong:
- ```contour``` layer is under the ```mountain_peak``` layer.
```json
"layers": [
    "housenumber", 
    "water_name", 
    "transportation_name", 
    "poi", 
    "place", 
    "transportation", 
    "building", 
    "aeroway", 
    "waterway", 
    "water", 
    "mountain_peak", 
    "boundary", 
    "contour", 
    "hillshade",
    "park", 
    "landuse", 
    "landcover"
  ], 
  "styles": [
    "voyager/style.mss", 
    "shared/admin.mss", 
    "shared/terrain.mss",
    "shared/hydro.mss", 
    "shared/landuse.mss", 
    "shared/roads.mss", 
    "shared/labels.mss"
  ], 
```
- i tried putting the definition one after each other without success
```less
#contour
  [zoom>=12][ele>300],
  [zoom>=14][ele>200],
  [zoom>=16][ele>0] {
  [index=5][zoom>=14],
  [index=10] {
    text-name: [ele]+' m';
    text-face-name: @mont;
    text-fill: #28521c;
    text-halo-fill: rgba(255,255,255,0.7);
    text-halo-radius: 1;
    text-avoid-edges: true;
    text-allow-overlap: false;
    text-halo-rasterizer: fast;
    text-placement: line;
    text-size: linear([view::zoom], (15, 8), (20, 12.0));
}
}

//Peak labels
#mountain_peak {
    [zoom>=4][comment =~'.*Highest.*'],
    [zoom>=4][comment =~'.*highest.*'],
    [zoom>=6][ele>=1000],
    [zoom>=8][ele>=1500],
    [zoom>=9][elevation>=500] {
    ::icon {
      marker-fill:#ff0000;

      marker-line-color: #ff0000;
      marker-file:url(icons/mountain_peak-11.svg);
    }
    ::label {
      text-name: @name ?  (@name + '\n'  + [ele] + 'm'): '';
      text-face-name: @mont;
        text-size: linear([view::zoom], (8, 9.0), (14, 12)) + [ele] * 0.00001;
      text-fill: @peak_label;
      text-halo-fill: @peak_halo;
      text-halo-radius: 1;
      text-halo-rasterizer: fast;
      text-wrap-width: 70;
      text-line-spacing:	-1;
      text-dy: 8;
    }
  }
}
```

**Comment by farfromrefug** [comment] 2019-05-21 12:27
@mtehver actually just found something weird. I feel lost
If i move the countour layer on top of mountain_peak, it works.
But shouldn't the order of layers in the json be "first drawn last" ? i mean as you can see in my json the landcover is last as it should be drawn first. I would the expect the labels priority to be like :
- first have higher priority than nexts

**Comment by farfromrefug** [comment] 2019-05-21 13:16
another issue with some marker SVGs. it seems like it is drawn with a "stroke". tried to use ```marker-line-width``` without success
<img width="1069" alt="Screen Shot 2019-05-21 at 15 14 11" src="https://user-images.githubusercontent.com/655344/58099056-2b898d80-7bdb-11e9-8ce9-e05f5404a69e.png">

**Comment by mtehver** [comment] 2019-05-21 13:47
@farfromrefug  About the layer ordering in json file - we copied the 'reverse order' behaviour from MapBox Studio Classic, I believe. Internally the order is reversed.

About using SVG files - we internally render SVG to a bitmap first and basically ignore most `marker-X` CSS parameters. This is different from Mapnik, if I remember correctly. But I would set a really low priority to fixing this.

Regarding the distance calculation - note that the feature point may be very far from the click position (at zoom=0, for example). Thus the ordering calculated based on this can be arbitrary.

**Comment by farfromrefug** [comment] 2019-05-21 13:56
@mtehver about the order thing. It means i can't do what i want? i mean:
- contour lines drawn under mountain peaks
- mountain peaks label getting priority over contour lines labels
That reversed order thing seems really weird to me.

About SVGs. How do i set the priority? :s Might switch to png then as it would better performances as you transform SVGs to PNGs

Regarding the distance, i dont think i get your point. As i use ```mapToScreen``` the positions on screen should be computed at the current zoom. So the distance comparaison can be done for all features. I think...

**Comment by mtehver** [comment] 2019-08-30 11:26
Closing as I think the real issues discussed here have been fixed. If anything needs additional attention, feel free to create additional issues.

**Closed by mtehver** 2019-08-30 11:26 UTC
