### ISSUE TITLE
impossible to change watermark after first render

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#405] opened 2020-12-21 16:01 UTC
In my use of the CartoSDK the place where i can call `getOptions().setWatermarkScale` is async and often happen after the map first render call.
The issue is that even if the `MapRenderer` gets option update notification the renderer will then always ignore it.
The issue happens [here](https://github.com/CartoDB/mobile-sdk/blob/651fa0aa87174b269eac3cdca3a2b00d7a9d540b/all/native/renderers/WatermarkRenderer.cpp#L95)
The only case where we would go inside is if the bitmap changed.

BTW on that note there is no way to use a custom bitmap for the watermark, even though the option is there. The `watermark` property needs to be set to `custom` from `getOptions().setWatermarkBitmap`
It would be cool to be able to do that for project not actually using carto data(license key).

**Comment by mtehver** [comment] 2020-12-22 08:12
Good find, you are right about this. I will fix this. Regarding `setWatermarkBitmap`, this only works for CARTO Enterprise licenses. This is actually mentioned in the API documentation, so it is so by design. It is partly an artifact from times when SDK was still closed source, but we plan to keep it.

**Comment by farfromrefug** [comment] 2020-12-22 08:17
@mtehver no problem about the license bitmap. I am just thinking that the carto SDK being a fully open source SDK which can be used with OSS data, it would be nice to be able to change the bitmap. Also with what s happening with Mapbox, Carto SDK could take a big place in the OSS world (which i really hope).

**Comment by mtehver** [comment] 2020-12-22 09:27
Ok, the argument makes sense. We will discuss it internally first.

Regarding the original issue, the fix is now in the master branch.

**Comment by farfromrefug** [comment] 2020-12-29 14:31
@mtehver i can confirm it is fixed now!

**Comment by mtehver** [comment] 2021-06-09 10:28
Closing the issue, the fix was implemented in SDK 4.3.4.

**Closed by mtehver** 2021-06-09 10:28 UTC
